trigger:
- master

resources:
  repositories:
  - repository: test2   # The name used to reference this repository in the checkout step
    type: github
    name: Shourabh28/test2
    endpoint: Shourabh28
    #ref: string  # ref name to use; defaults to 'refs/heads/master'

#pool: 'Testing'

variables:
  name: hello-world

stages:
- stage: 'GetFiles'
  jobs:
  - job: A
    steps:
    - checkout: self
    - checkout: test2
    - script: |
        echo $(Build.SourcesDirectory)
        ls $(Build.SourcesDirectory) *
